### ISSUE TITLE
Question: How to load data

### ISSUE THREAD

**Issue by Rhinogradentia** [TAMU-CPT/blastview#1]
Hi there,

I want to try out this tool and have one question. I've already created a gff3 file from the xml-blast-output with the tool you mention in README.

My question is now if this gff is loaded like any other gff with the flatfile-to-json script or if I have to edit it beforehand. The reason I am asking is, that the first column of the gff refers to the ID of the hit (e.g. gene) instead of the referring chromosome.

Thank you in advance
Best Regards,
Nadine

**Comment by Rhinogradentia** [comment]
I've managed to load the data successfully. 
So, for anyone else who might need this, following the workflow:

- the genome has to be the query, not the features
`
blastn -subject genes.fasta  -query genome.fasta -out out_blastn.xml -outfmt 5
`
- parsing into gff file
`
python blastxml_to_gapped_gff3.py --include_seq  out_blastn.xml > out_blastn.gff3
`
- load into jbrowse
`
bin/flatfile-to-json.pl --gff out_blastn.gff3 --trackLabel blastTrack --key "Blast Hits" --trackType "BlastView/View/Track/CanvasFeatures"
`

The track can be edited after loading. I added the glyph, a category and a color.

**Comment by hexylena** [comment]
Sorry for the delayed response. Author here, back from holiday

If you're using `blastn`, you'll want to use https://github.com/TAMU-CPT/galaxy-tools/blob/master/tools/blast/blastxml_to_gapped_gff3-nt.py to ensure that the widths are correct. It can be invoked identically to the other version which is specific for protein data. Please let me know if you have any questions!

**Comment by Rhinogradentia** [comment]
Thank you - I will use this script and redo the rest.
